id: P848B4141
initial_creation_type: ocr
source_metadata:
  volumes:
    c415bf25816946a29e796d54d432d7f4:
      base_file: v016.txt
      image_group_id: I1PD95861
      title: སྒྲོན་མ་གསལ་བར་བྱེད་པའི་དགོངས་པ་རབ་གསལ་ཞེས་བྱ་བ་བཤད་པའི་ཊཱི་ཀཱ།
      total_pages: 1354
      volume_number: 16
